"""initial schema

Revision ID: aa9ba08e9ff9
Revises: 
Create Date: 2026-09-29 22:36:53.490261
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'aa9ba08e9ff9'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agent', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('tickets',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False, start=10000), nullable=False),
    sa.Column('subject', sa.String(length=998), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_html', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'in_progress', 'pending_customer', 'resolved', 'closed', name='ticket_status'), server_default='open', nullable=False),
    sa.Column('priority', sa.Enum('low', 'normal', 'high', 'urgent', name='ticket_priority'), server_default='normal', nullable=False),
    sa.Column('source', sa.Enum('email', 'web', 'system', name='message_source'), nullable=False),
    sa.Column('requester_email', sa.String(length=320), nullable=False),
    sa.Column('requester_name', sa.String(length=200), nullable=True),
    sa.Column('assigned_to_id', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('message_id', sa.String(length=998), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), sa.Computed("setweight(to_tsvector('english', coalesce(subject, '')), 'A') || setweight(to_tsvector('english', coalesce(description, '')), 'B')", persisted=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], name=op.f('fk_tickets_assigned_to_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tickets_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tickets')),
    sa.UniqueConstraint('message_id', name=op.f('uq_tickets_message_id'))
    )
    op.create_index('ix_tickets_assignee_status', 'tickets', ['assigned_to_id', 'status'], unique=False)
    op.create_index(op.f('ix_tickets_requester_email'), 'tickets', ['requester_email'], unique=False)
    op.create_index('ix_tickets_search_vector', 'tickets', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('ix_tickets_status_last_activity', 'tickets', ['status', sa.literal_column('last_activity_at DESC')], unique=False)
    op.create_index('ix_tickets_unassigned_active', 'tickets', [sa.literal_column('created_at DESC')], unique=False, postgresql_where=sa.text("assigned_to_id IS NULL AND status IN ('open', 'in_progress', 'pending_customer')"))
    op.create_table('ticket_comments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('author_email', sa.String(length=320), nullable=True),
    sa.Column('author_name', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('is_internal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    # message_source was already created with the tickets table.
    sa.Column('source', postgresql.ENUM('email', 'web', 'system', name='message_source', create_type=False), nullable=False),
    sa.Column('message_id', sa.String(length=998), nullable=True),
    sa.Column('in_reply_to', sa.String(length=998), nullable=True),
    sa.Column('email_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'sent', 'failed', name='delivery_status'), nullable=True),
    sa.Column('delivery_error', sa.Text(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_ticket_comments_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_comments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_comments')),
    sa.UniqueConstraint('message_id', name=op.f('uq_ticket_comments_message_id'))
    )
    op.create_index('ix_ticket_comments_ticket_created', 'ticket_comments', ['ticket_id', 'created_at'], unique=False)
    op.create_index('ix_ticket_comments_undelivered', 'ticket_comments', ['delivery_status'], unique=False, postgresql_where=sa.text("delivery_status IN ('pending', 'failed')"))
    op.create_table('ticket_attachments',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('ticket_id', sa.BigInteger(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=True),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['ticket_comments.id'], name=op.f('fk_ticket_attachments_comment_id_ticket_comments'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], name=op.f('fk_ticket_attachments_ticket_id_tickets'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ticket_attachments'))
    )
    op.create_index(op.f('ix_ticket_attachments_comment_id'), 'ticket_attachments', ['comment_id'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_sha256'), 'ticket_attachments', ['sha256'], unique=False)
    op.create_index(op.f('ix_ticket_attachments_ticket_id'), 'ticket_attachments', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticket_attachments_ticket_id'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_sha256'), table_name='ticket_attachments')
    op.drop_index(op.f('ix_ticket_attachments_comment_id'), table_name='ticket_attachments')
    op.drop_table('ticket_attachments')
    op.drop_index('ix_ticket_comments_undelivered', table_name='ticket_comments', postgresql_where=sa.text("delivery_status IN ('pending', 'failed')"))
    op.drop_index('ix_ticket_comments_ticket_created', table_name='ticket_comments')
    op.drop_table('ticket_comments')
    op.drop_index('ix_tickets_unassigned_active', table_name='tickets', postgresql_where=sa.text("assigned_to_id IS NULL AND status IN ('open', 'in_progress', 'pending_customer')"))
    op.drop_index('ix_tickets_status_last_activity', table_name='tickets')
    op.drop_index('ix_tickets_search_vector', table_name='tickets', postgresql_using='gin')
    op.drop_index(op.f('ix_tickets_requester_email'), table_name='tickets')
    op.drop_index('ix_tickets_assignee_status', table_name='tickets')
    op.drop_table('tickets')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_table('users')
    for enum_name in ('delivery_status', 'message_source', 'ticket_priority', 'ticket_status', 'user_role'):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
